/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mantenimientos;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diana
 */
public class MatenimientoClientes extends javax.swing.JFrame {
   
        
    /**
     * Creates new form MatenimientoClientes
     */
    public MatenimientoClientes() {
        initComponents();
        this.tabladedatos.setModel(model);
        this.model.addColumn("Codigo");
        this.model.addColumn("Empleado");
        this.model.addColumn("Telefono");
        this.model.addColumn("Sexo");
        this.model.addColumn("Cargo");
        this.model.addColumn("Fecha de Contrato");
        this.model.addColumn("Sueldo");
    
        
        this.tabladedatos.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    DefaultTableModel model=new DefaultTableModel();
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladedatos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtempleado = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        comcargo = new javax.swing.JComboBox<>();
        txtsueldo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Label_status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO EMPLEADOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        tabladedatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabladedatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladedatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabladedatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 723, 202));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EMPLEADO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CARGO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FECHA DE CONTRATO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SUELDO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 170, -1));
        getContentPane().add(txtempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 170, -1));
        getContentPane().add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 170, -1));

        comcargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "Contador", "Auxiliar", "Secretaria", "Vendedora", "Chofer", "Mensajero" }));
        comcargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comcargoActionPerformed(evt);
            }
        });
        getContentPane().add(comcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 170, -1));
        getContentPane().add(txtsueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 170, -1));

        jButton2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 170, -1));

        jButton3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 170, -1));

        jButton4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 170, -1));

        jButton1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 170, -1));

        jButton5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton5.setText("SALIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 130, -1));

        jButton6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton6.setText("Buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 170, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CODIGO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 30, 20));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 120, -1));

        jButton7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton7.setText("REGRESAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 130, -1));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_status.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Label_status.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Label_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabladedatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladedatosMouseClicked
        // CONEXION MYSQL

        try {
            
            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost/Proyectofinal","root","");
            java.sql.PreparedStatement pst = cn.prepareStatement("insert into employee_record1 values(?,?,?,?,?,?)");

            pst.setString(1, "0");
            pst.setString(2, txtcodigo.getText().trim());
            pst.setString(3, txtempleado.getText().trim());
            pst.setString(4, comcargo.getSelectedItem().toString());
            pst.setString(5, txtfecha.getText().trim());
            pst.setString(6, txtsueldo.getText().trim());

            pst.executeUpdate();

            txtcodigo.setText("");
            txtempleado.setText("");
            comcargo.setSelectedItem("");
            txtfecha.setText("");
            txtsueldo.setText("");

            Label_status.setText("Registro exitoso");

        } catch (Exception e) {

        }

        //-----------------------------------------------------------------------------------------------------//
        //CODIGO R_EMPLEADOS
        int fila_seleccionada=tabladedatos.getSelectedRow();
        txtcodigo.setText(tabladedatos.getValueAt(fila_seleccionada,0).toString());
        txtempleado.setText(tabladedatos.getValueAt(fila_seleccionada,1).toString());
        comcargo.setSelectedItem(tabladedatos.getValueAt(fila_seleccionada,2).toString());
        txtfecha.setText(tabladedatos.getValueAt(fila_seleccionada,3).toString());
        txtsueldo.setText(tabladedatos.getValueAt(fila_seleccionada,4).toString());
        int filas_selaeccionada = 0;
        filas=filas_selaeccionada;

    }//GEN-LAST:event_tabladedatosMouseClicked

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void comcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comcargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comcargoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // CONEXION MYSQL
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost/Proyectofinal","root","");

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/Proyectofinal", "root", "");//conecta a MYSQL
            java.sql.PreparedStatement pst = cn.prepareStatement("insert into employee_record1 values(?,?,?,?,?,?)");

            pst.setString(1, "0");
            pst.setString(2, txtcodigo.getText().trim());
            pst.setString(3, txtempleado.getText().trim());
            pst.setString(4, comcargo.getSelectedItem().toString());
            pst.setString(5, txtfecha.getText().trim());
            pst.setString(6, txtsueldo.getText().trim());

            pst.executeUpdate();

            txtcodigo.setText("");
            txtempleado.setText("");
            comcargo.getSelectedItem().toString();
            txtfecha.setText("");
            txtsueldo.setText("");

            Label_status.setText("Registro exitoso.");

        }catch (Exception e){
            e.printStackTrace();
        }
        //---------------------------------------------------------------------------------------------------//
        //CODIGO R_EMPLEADOS
        this.txtcodigo.setText("");
        this.txtempleado.setText("");
        this.comcargo.setSelectedIndex(0);
        this.txtfecha.setText("");
        this.txtsueldo.setText("");
        txtcodigo.grabFocus();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // CONEXION MYSQL MODIFICAR

        try {
            String ID = txtid.getText().trim();

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/Proyectofinal", "root", "");
            java.sql.PreparedStatement pst = cn.prepareStatement("update employee_record1 set Codigo=?,  CodigoEmpleado=?,  CodigoCargo=?, CodigoFecha = ?,  CodigoSueldo = ?  where ID = " + ID);

            pst.setString(1, txtcodigo.getText().trim());
            pst.setString(2, txtempleado.getText().trim());
            pst.setString(3, comcargo.getSelectedItem().toString());
            pst.setString(4, txtfecha.getText().trim());
            pst.setString(5, txtsueldo.getText().trim());

            pst.executeUpdate();

            Label_status.setText("Modificación exitosa.");

        } catch (Exception e) {
        }

        //-----------------------------------------------------------------------------------------------------//
        // CODIGO R_EMPLEADOS

        String [] datos=new String [5];
        datos[0]=txtcodigo.getText();
        datos[1]=txtempleado.getText();
        datos[2]=comcargo.getSelectedItem().toString();
        datos[3]=txtfecha.getText();
        datos[4]=txtsueldo.getText();
        int i = 0;

        for (int a  = 0; a < tabladedatos.getColumnCount(); a++) {
            model.setValueAt(datos[a],filas, a );
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // int fila_seleccionada=tablaempleado.getSelectedRow();
        // if(fila_seleccionada>=0){
            //     modelo.removeRow(fila_seleccionada);
            // }else{
            //     JOptionPane.showMessageDialog(null, "seleccione una fila por favor");
            // }
        //CODIGO CONEXION
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/Proyectofinal", "root", "");
            java.sql.PreparedStatement pst = cn.prepareStatement("delete from employee_record1 where ID = ?");

            pst.setString(1, txtid.getText().trim());

            pst.executeUpdate();
            txtcodigo.setText("");
            txtempleado.setText("");
            comcargo.setSelectedItem("");
            txtfecha.setText("");
            txtsueldo.setText("");

            Label_status.setText("Registro eliminado.");

        } catch (Exception e) {
        }

        //---------------------------------------------------------------------------------------------------------------//
        //CODIGO R_EMPLEADOS
        DefaultTableModel modelo = (DefaultTableModel) tabladedatos.getModel();
        int a=tabladedatos.getSelectedRow();
        if (a<0){
            //JOptionPane.showMessageDialog(null, "Debe seleccionar una fila");
        }else{
            int confirmar = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar el registro?");
            if (JOptionPane.OK_OPTION == confirmar){
                modelo.removeRow(a);
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // CONEXION MYSQL
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost/Proyectofinal","root","");

            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost/Proyectofinal","root","");
            java.sql.PreparedStatement pst = cn.prepareStatement("insert into employee_record1 values(?,?,?,?,?,?)");

            pst.setString(1, "0");
            pst.setString(2, txtcodigo.getText().trim());
            pst.setString(3, txtempleado.getText().trim());
            pst.setString(4, comcargo.getSelectedItem().toString());
            pst.setString(5, txtfecha.getText().trim());
            pst.setString(6, txtsueldo.getText().trim());

            pst.executeUpdate();

            txtcodigo.setText("");
            txtempleado.setText("");
            comcargo.setSelectedItem("");
            txtfecha.setText("");
            txtsueldo.setText("");

            Label_status.setText("Registro exitoso");

        } catch (Exception e) {

        }

        //-----------------------------------------------------------------------------------------------------------------------------------------------------//
        // CODIGO R_EMPLEADOS

        this.model.addRow(new Object [] {
            this.txtcodigo.getText(),this.txtempleado.getText(), this.comcargo.getSelectedItem(),this.txtfecha.getText(),this.txtsueldo.getText()
        });
        this.txtcodigo.setText("");
        this.txtempleado.setText("");
        this.comcargo.setSelectedIndex(0);
        this.txtfecha.setText("");
        this.txtsueldo.setText("");
        txtcodigo.grabFocus();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //BOTON BUSCAR
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/Proyectofinal", "root", "");
            java.sql.PreparedStatement pst = cn.prepareStatement("select * from employee_record1 where ID = ?");
            pst.setString(1, txtid.getText().trim());

            ResultSet rs = pst.executeQuery();

            if(rs.next()){

                txtcodigo.setText(rs.getString("Codigo"));
                txtempleado.setText(rs.getString("CodigoEmpleado"));
                comcargo.setSelectedItem(rs.getString("CodigoCargo"));
                txtfecha.setText(rs.getString("CodigoFecha"));
                txtsueldo.setText(rs.getString("CodigoSueldo"));

            } else {
                JOptionPane.showMessageDialog(null, "Persona no registrada.");
            }

        }catch (Exception e){

        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
//        Contenedor GN= new Contenedor();
//        GN.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    

    /**
     * @param args the command line arguments
     */
    int filas;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatenimientoClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatenimientoClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatenimientoClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatenimientoClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatenimientoClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_status;
    private javax.swing.JComboBox<String> comcargo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladedatos;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtempleado;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtsueldo;
    // End of variables declaration//GEN-END:variables
}
