/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RENTA_VEHICULOS;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vista.menu;

/**
 *
 * @author Diana
 */
public class Renta extends javax.swing.JFrame {
    
    /**
     * Creates new form Renta
     */
    public Renta() {
        initComponents();
        this.tabladedatos.setModel(model);
        this.model.addColumn("Codigo");
        this.model.addColumn("ID_RENTA");
        this.model.addColumn("SERIE");
        this.model.addColumn("ID_CLIENTE");
        this.model.addColumn("ID_USUARIO");
        this.model.addColumn("ID_TIPO_PAGO");
        this.model.addColumn("FECHA_PRESTAMO");
        this.model.addColumn("FECHA_DEVOLUCION");
        this.model.addColumn("TOTAL");
       
        
        this.tabladedatos.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    DefaultTableModel model=new DefaultTableModel();
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladedatos = new javax.swing.JTable();
        Label_status = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtid = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        txtidrenta = new javax.swing.JTextField();
        txtserie = new javax.swing.JTextField();
        txtcliente = new javax.swing.JTextField();
        txtususario = new javax.swing.JTextField();
        txttipopago = new javax.swing.JTextField();
        txtfechaprestamo = new javax.swing.JTextField();
        txtdevolucionfecha = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("ID_RENTA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 127, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("ID_CLIENTE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("ID_USUARIO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("ID_TIPO_PAGO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("FECHA_PRESTAMO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("FECHA_DEVOLUCION");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("TOTAL");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 170, -1));

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 170, -1));

        jButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 170, -1));

        jButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 170, -1));

        jButton6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton6.setText("Buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 170, -1));

        jButton5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton5.setText("SALIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 170, -1));

        tabladedatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabladedatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 430, 720, 137));
        getContentPane().add(Label_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 90, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 119, -1));
        jPanel1.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 118, -1));
        jPanel1.add(txtidrenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 118, -1));
        jPanel1.add(txtserie, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 118, -1));
        jPanel1.add(txtcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 118, -1));
        jPanel1.add(txtususario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 118, -1));
        jPanel1.add(txttipopago, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 118, -1));
        jPanel1.add(txtfechaprestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 118, -1));
        jPanel1.add(txtdevolucionfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 118, -1));
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 120, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("CODIGO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("SERIE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jButton7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton7.setText("REGRESAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 170, -1));

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("RENTA");
        jPanel3.add(jLabel12);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // REGISTRAR
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost/Proyecto_renta","root","");

            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost/Proyecto_renta","root","");
            java.sql.PreparedStatement pst = cn.prepareStatement("insert into RENTA values(?,?,?,?,?,?,?,?,?,?)");

            pst.setString(1, "0");
            pst.setString(2, txtcodigo.getText().trim());
            pst.setString(3, txtidrenta.getText().trim());
            pst.setString(4, txtserie.getText().trim());
            pst.setString(5, txtcliente.getText().trim());
            pst.setString(6, txtususario.getText().trim());
            pst.setString(7, txttipopago.getText().trim());
            pst.setString(8, txtfechaprestamo.getText().trim());
            pst.setString(9, txtdevolucionfecha.getText().trim());
            pst.setString(10, txttotal.getText().trim());
            
            
            pst.executeUpdate();

            txtcodigo.setText("");
            txtidrenta.setText("");
            txtserie.setText("");
            txtcliente.setText("");
            txtususario.setText("");
            txttipopago.setText("");
            txtfechaprestamo.setText("");
            txtdevolucionfecha.setText("");
            txttotal.setText("");
            
            Label_status.setText("Registro exitoso");

        } catch (Exception e) {

        }

        //-----------------------------------------------------------------------------------------------------------------------------------------------------//
        // CODIGO TABLA RENTA

        this.model.addRow(new Object [] {
            this.txtcodigo.getText(),this.txtidrenta.getText(), this.txtserie.getText(),this.txtcliente.getText(),this.txtususario.getText(),this.txttipopago.getText(),this.txtfechaprestamo.getText(),this.txtdevolucionfecha.getText(), this.txttotal.getText()
        });
        this.txtcodigo.setText("");
        this.txtidrenta.setText("");
        this.txtserie.setText("");
        this.txtcliente.setText("");
        this.txtususario.setText("");
        this.txttipopago.setText("");
        this.txtfechaprestamo.setText("");
        this.txtdevolucionfecha.setText("");
        this.txttotal.setText("");
        
        txtcodigo.grabFocus();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // 
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost/Proyecto_renta","root","");

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/Proyecto_renta", "root", "");//conecta a MYSQL
            java.sql.PreparedStatement pst = cn.prepareStatement("insert into RENTA values(?,?,?,?,?,?,?,?,?,?)");

            pst.setString(1, "0");
            pst.setString(2, txtcodigo.getText().trim());
            pst.setString(3, txtidrenta.getText().trim());
            pst.setString(4, txtserie.getText().trim());
            pst.setString(5, txtcliente.getText().trim());
            pst.setString(6, txtususario.getText().trim());
            pst.setString(7, txttipopago.getText().trim());
            pst.setString(8, txtfechaprestamo.getText().trim());
            pst.setString(9, txtdevolucionfecha.getText().trim());
            pst.setString(10, txttotal.getText().trim());
            
            pst.executeUpdate();

            txtcodigo.setText("");
            txtidrenta.setText("");           
            txtserie.setText("");
            txtcliente.setText("");
            txtususario.setText("");
            txttipopago.setText("");
            txtfechaprestamo.setText("");
            txtdevolucionfecha.setText("");
            txttotal.setText("");
              
            Label_status.setText("Registro exitoso.");

        }catch (Exception e){
            e.printStackTrace();
        }
        //---------------------------------------------------------------------------------------------------//
        //CODIGO TABLA RENTA
        this.txtcodigo.setText("");
        this.txtidrenta.setText("");
        this.txtserie.setText("");
        this.txtcliente.setText("");
        this.txtususario.setText("");
        this.txttipopago.setText("");
        this.txtfechaprestamo.setText("");
        this.txtdevolucionfecha.setText("");
        this.txttotal.setText("");
         
        txtcodigo.grabFocus();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // CONEXION MYSQL MODIFICAR

        try {
            String ID = txtid.getText().trim();

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/Proyecto_renta", "root", "");
            java.sql.PreparedStatement pst = cn.prepareStatement("update RENTA set Codigo=?,  ID_RENTA=?,  SERIE=?, ID_CLIENTE = ?,  ID_USUARIO = ?, ID_TIPO_PAGO = ?, FECHA_PRESTAMO = ?, FECHA_DEVOLUCION = ?, TOTAL = ?  where ID = " + ID);

            pst.setString(1, txtcodigo.getText().trim());
            pst.setString(2, txtidrenta.getText().trim());
            pst.setString(3, txtserie.getText().trim());
            pst.setString(4, txtcliente.getText().trim());
            pst.setString(5, txtususario.getText().trim());
            pst.setString(6, txttipopago.getText().trim());
            pst.setString(7, txtfechaprestamo.getText().trim());
            pst.setString(8, txtdevolucionfecha.getText().trim());
            pst.setString(9, txttotal.getText().trim());
            
            pst.executeUpdate();

            Label_status.setText("Modificación exitosa.");

        } catch (Exception e) {
        }

        //-----------------------------------------------------------------------------------------------------//
        // CODIGO R_EMPLEADOS

        String [] datos=new String [9];
        datos[0]=txtcodigo.getText();
        datos[1]=txtidrenta.getText();
        datos[2]=txtserie.getText();
        datos[3]=txtcliente.getText();
        datos[4]=txtususario.getText();
        datos[5]=txttipopago.getText();
        datos[6]=txtfechaprestamo.getText();
        datos[7]=txtdevolucionfecha.getText();
        datos[8]=txttotal.getText();
        
        int i = 0;

        for (int a  = 0; a < tabladedatos.getColumnCount(); a++) {
            model.setValueAt(datos[a],filas, a );
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/Proyecto_renta", "root", "");
            java.sql.PreparedStatement pst = cn.prepareStatement("delete from RENTA where ID = ?");

            pst.setString(1, txtid.getText().trim());

            pst.executeUpdate();
            txtcodigo.setText("");
            txtidrenta.setText("");
            txtserie.setText("");
            txtcliente.setText("");
            txtususario.setText("");
            txttipopago.setText("");
            txtfechaprestamo.setText("");
            txtdevolucionfecha.setText("");
            txttotal.setText("");
            

            Label_status.setText("Registro eliminado.");

        } catch (Exception e) {
        }

        //---------------------------------------------------------------------------------------------------------------//
        //CODIGO R_EMPLEADOS
        DefaultTableModel modelo = (DefaultTableModel) tabladedatos.getModel();
        int a=tabladedatos.getSelectedRow();
        if (a<0){
            //JOptionPane.showMessageDialog(null, "Debe seleccionar una fila");
        }else{
            int confirmar = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar el registro?");
            if (JOptionPane.OK_OPTION == confirmar){
                modelo.removeRow(a);
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //BOTON BUSCAR
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/Proyecto_renta", "root", "");
            java.sql.PreparedStatement pst = cn.prepareStatement("select * from RENTA where ID = ?");
            pst.setString(1, txtid.getText().trim());

            ResultSet rs = pst.executeQuery();

            if(rs.next()){

                txtcodigo.setText(rs.getString("Codigo"));
                txtidrenta.setText(rs.getString("ID_RENTA"));
                txtserie.setText(rs.getString("SERIE"));
                txtcliente.setText(rs.getString("ID_CLIENTE"));  
                txtususario.setText(rs.getString("ID_USUARIO"));
                txttipopago.setText(rs.getString("ID_TIPO_PAGO"));
                txtfechaprestamo.setText(rs.getString("FECHA_PRESTAMO"));
                txtdevolucionfecha.setText(rs.getString("FECHA_DEVOLUCION"));
                txttotal.setText(rs.getString("TOTAL"));
                

            } else {
                JOptionPane.showMessageDialog(null, "Persona no registrada.");
            }

        }catch (Exception e){

        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        menu GN= new menu();
        GN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
        int filas;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Renta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_status;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladedatos;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdevolucionfecha;
    private javax.swing.JTextField txtfechaprestamo;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidrenta;
    private javax.swing.JTextField txtserie;
    private javax.swing.JTextField txttipopago;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtususario;
    // End of variables declaration//GEN-END:variables
}
