/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RENTA_VEHICULOS;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vista.menu;

/**
 *
 * @author Diana
 */
public class Vehiculos extends javax.swing.JFrame {

    /**
     * Creates new form Vehiculos
     */
    public Vehiculos() {
        initComponents();
        this.tabladedatos.setModel(model);
        this.model.addColumn("Codigo");
        this.model.addColumn("ID_VEHICULO");
        this.model.addColumn("ID_MARCA");
        this.model.addColumn("ID_TIPO_VEHICULO");
        this.model.addColumn("ID_VEHICULO_ESTADO");
        this.model.addColumn("MODELO");
       
    
        
        this.tabladedatos.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     DefaultTableModel model=new DefaultTableModel();
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladedatos = new javax.swing.JTable();
        Label_status = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        txtidvehiculo = new javax.swing.JTextField();
        txtmarca = new javax.swing.JTextField();
        txtidtipovehiculo = new javax.swing.JTextField();
        txtestadovegiculo = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 77, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("CODIGO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 108, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("ID_VEHICULO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 139, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("ID_MARCA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 167, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("ID_TIPO_VEHICULO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("ID_VEHICULO_ESTADO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 221, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("MODELO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 252, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("VEHICULOS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 150, -1));

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 150, -1));

        jButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 150, 20));

        jButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 150, -1));

        jButton6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton6.setText("Buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 150, -1));

        jButton5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton5.setText("SALIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 150, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabladedatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabladedatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 345, 678, 131));
        jPanel1.add(Label_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 298, 117, 26));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 140, -1));
        jPanel1.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 140, -1));
        jPanel1.add(txtidvehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 140, -1));
        jPanel1.add(txtmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 140, -1));
        jPanel1.add(txtidtipovehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 140, -1));
        jPanel1.add(txtestadovegiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 140, -1));
        jPanel1.add(txtmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 140, -1));

        jButton7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton7.setText("REGRESAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // CONEXION MYSQL
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost/Proyecto_renta","root","");

            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost/Proyecto_renta","root","");
            java.sql.PreparedStatement pst = cn.prepareStatement("insert into VEHICULO values(?,?,?,?,?,?,?)");

            pst.setString(1, "0");
            pst.setString(2, txtcodigo.getText().trim());
            pst.setString(3, txtidvehiculo.getText().trim());
            pst.setString(4, txtmarca.getText().trim());
            pst.setString(5, txtidtipovehiculo.getText().trim());
            pst.setString(6, txtestadovegiculo.getText().trim());
            pst.setString(7, txtmodelo.getText().trim());

            pst.executeUpdate();

            txtcodigo.setText("");
            txtidvehiculo.setText("");
            txtmarca.setText("");
            txtidtipovehiculo.setText("");
            txtestadovegiculo.setText("");
            txtmodelo.setText("");

            Label_status.setText("Registro exitoso");

        } catch (Exception e) {

        }

        //-----------------------------------------------------------------------------------------------------------------------------------------------------//
        // CODIGO VEHICULO

        this.model.addRow(new Object [] {
            this.txtcodigo.getText(),this.txtidvehiculo.getText(), this.txtmarca.getText(),this.txtidtipovehiculo.getText(), this.txtestadovegiculo.getText(),this.txtmodelo.getText()
        });
        this.txtcodigo.setText("");
        this.txtidvehiculo.setText("");
        this.txtmarca.setText("");
        this.txtidtipovehiculo.setText("");
        this.txtestadovegiculo.setText("");
        this.txtmodelo.setText("");
        
        txtcodigo.grabFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // CONEXION MYSQL
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost/Proyecto_renta","root","");

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/Proyecto_renta", "root", "");//conecta a MYSQL
            java.sql.PreparedStatement pst = cn.prepareStatement("insert into VEHICULO values(?,?,?,?,?,?,?)");

            pst.setString(1, "0");
            pst.setString(2, txtcodigo.getText().trim());
            pst.setString(3, txtidvehiculo.getText().trim());
            pst.setString(4, txtmarca.getText().trim());
            pst.setString(5, txtidtipovehiculo.getText().trim());
            pst.setString(6, txtestadovegiculo.getText().trim());
            pst.setString(7, txtmodelo.getText().trim());

            pst.executeUpdate();

            txtcodigo.setText("");
            txtidvehiculo.setText("");
            txtmarca.setText("");
            txtidtipovehiculo.setText("");
            txtestadovegiculo.setText("");
            txtmodelo.setText("");

            Label_status.setText("Registro exitoso.");

        }catch (Exception e){
            e.printStackTrace();
        }
        //---------------------------------------------------------------------------------------------------//
        //CODIGO VEHICULO
        this.txtcodigo.setText("");
        this.txtidvehiculo.setText("");
        this.txtmarca.setText("");
        this.txtidtipovehiculo.setText("");
        this.txtestadovegiculo.setText("");
        this.txtmodelo.setText("");

        txtcodigo.grabFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // CONEXION MYSQL MODIFICAR

        try {
            String ID = txtid.getText().trim();

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/Proyecto_renta", "root", "");
            java.sql.PreparedStatement pst = cn.prepareStatement("update VEHICULO set Codigo=?,  ID_VEHICULO=?,  ID_MARCA=?, ID_TIPO_VEHICULO = ?,  ID_VEHICULO_ESTADO = ?, MODELO=?  where ID = " + ID);

            pst.setString(1, txtcodigo.getText().trim());
            pst.setString(2, txtidvehiculo.getText().trim());
            pst.setString(3, txtmarca.getText().trim());
            pst.setString(4, txtidtipovehiculo.getText().trim());
            pst.setString(5, txtestadovegiculo.getText().trim());
            pst.setString(6, txtmodelo.getText().trim());

            pst.executeUpdate();

            Label_status.setText("Modificación exitosa.");

        } catch (Exception e) {
        }

        //-----------------------------------------------------------------------------------------------------//
        // CODIGO R_EMPLEADOS

        String [] datos=new String [6];
        datos[0]=txtcodigo.getText();
        datos[1]=txtidvehiculo.getText();
        datos[2]=txtmarca.getText();
        datos[3]=txtidtipovehiculo.getText();
        datos[4]=txtestadovegiculo.getText();
        datos[5]=txtmodelo.getText();
        
        int i = 0;

        for (int a  = 0; a < tabladedatos.getColumnCount(); a++) {
            model.setValueAt(datos[a],filas, a );
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/Proyecto_renta", "root", "");
            java.sql.PreparedStatement pst = cn.prepareStatement("delete from VEHICULO where ID = ?");

            pst.setString(1, txtid.getText().trim());

            pst.executeUpdate();

            txtcodigo.setText("");
            txtidvehiculo.setText("");
            txtmarca.setText("");
            txtidtipovehiculo.setText("");
            txtestadovegiculo.setText("");
            txtmodelo.setText("");

            Label_status.setText("Registro eliminado.");

        } catch (Exception e) {
        }

        //---------------------------------------------------------------------------------------------------------------//
        //CODIGO R_EMPLEADOS
        DefaultTableModel modelo = (DefaultTableModel) tabladedatos.getModel();
        int a=tabladedatos.getSelectedRow();
        if (a<0){
            //JOptionPane.showMessageDialog(null, "Debe seleccionar una fila");
        }else{
            int confirmar = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar el registro?");
            if (JOptionPane.OK_OPTION == confirmar){
                modelo.removeRow(a);
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //BOTON BUSCAR
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/Proyecto_renta", "root", "");
            java.sql.PreparedStatement pst = cn.prepareStatement("select * from VEHICULO where ID = ?");

            pst.setString(1, txtid.getText().trim());

            ResultSet rs = pst.executeQuery();

            if(rs.next()){

                txtcodigo.setText(rs.getString("Codigo"));
                txtidvehiculo.setText(rs.getString("ID_VEHICULO"));
                txtmarca.setText(rs.getString("ID_MARCA"));
                txtidtipovehiculo.setText(rs.getString("ID_TIPO_VEHICULO"));
                txtestadovegiculo.setText(rs.getString("ID_VEHICULO_ESTADO"));
                txtmodelo.setText(rs.getString("MODELO"));

            } else {
                JOptionPane.showMessageDialog(null, "Persona no registrada.");
            }

        }catch (Exception e){

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        menu GN= new menu();
        GN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    int filas;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_status;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladedatos;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtestadovegiculo;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidtipovehiculo;
    private javax.swing.JTextField txtidvehiculo;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    // End of variables declaration//GEN-END:variables
}
